// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TRPFS_TITAN_FILESYSTEM_H_
#define FLATBUFFERS_GENERATED_TRPFS_TITAN_FILESYSTEM_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace Titan {
namespace FileSystem {

struct TRPFS;
struct TRPFSBuilder;

struct TRPFS FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TRPFSBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FILE_HASHES = 4,
    VT_FILE_OFFSETS = 6
  };
  const ::flatbuffers::Vector<uint64_t> *file_hashes() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_FILE_HASHES);
  }
  const ::flatbuffers::Vector<uint64_t> *file_offsets() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_FILE_OFFSETS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_FILE_HASHES) &&
           verifier.VerifyVector(file_hashes()) &&
           VerifyOffset(verifier, VT_FILE_OFFSETS) &&
           verifier.VerifyVector(file_offsets()) &&
           verifier.EndTable();
  }
};

struct TRPFSBuilder {
  typedef TRPFS Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_file_hashes(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> file_hashes) {
    fbb_.AddOffset(TRPFS::VT_FILE_HASHES, file_hashes);
  }
  void add_file_offsets(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> file_offsets) {
    fbb_.AddOffset(TRPFS::VT_FILE_OFFSETS, file_offsets);
  }
  explicit TRPFSBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TRPFS> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TRPFS>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TRPFS> CreateTRPFS(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> file_hashes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> file_offsets = 0) {
  TRPFSBuilder builder_(_fbb);
  builder_.add_file_offsets(file_offsets);
  builder_.add_file_hashes(file_hashes);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TRPFS> CreateTRPFSDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint64_t> *file_hashes = nullptr,
    const std::vector<uint64_t> *file_offsets = nullptr) {
  auto file_hashes__ = file_hashes ? _fbb.CreateVector<uint64_t>(*file_hashes) : 0;
  auto file_offsets__ = file_offsets ? _fbb.CreateVector<uint64_t>(*file_offsets) : 0;
  return Titan::FileSystem::CreateTRPFS(
      _fbb,
      file_hashes__,
      file_offsets__);
}

inline const Titan::FileSystem::TRPFS *GetTRPFS(const void *buf) {
  return ::flatbuffers::GetRoot<Titan::FileSystem::TRPFS>(buf);
}

inline const Titan::FileSystem::TRPFS *GetSizePrefixedTRPFS(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Titan::FileSystem::TRPFS>(buf);
}

inline bool VerifyTRPFSBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Titan::FileSystem::TRPFS>(nullptr);
}

inline bool VerifySizePrefixedTRPFSBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Titan::FileSystem::TRPFS>(nullptr);
}

inline void FinishTRPFSBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Titan::FileSystem::TRPFS> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTRPFSBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Titan::FileSystem::TRPFS> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace FileSystem
}  // namespace Titan

#endif  // FLATBUFFERS_GENERATED_TRPFS_TITAN_FILESYSTEM_H_
